#!/bin/sh
#BSUB -J relax
#BSUB -n 24
#BSUB -q 9242opa!

module load ips/2018u4
export I_MPI_ADJUST_REDUCE=3
export I_MPI_FABRICS=shm

mpirun -np ${LSB_DJOB_NUMPROC} vasp_std
cp CONTCAR POSCAR
cp POSCAR POSCAR1
NN=`grep "in kB" OUTCAR  | wc -l`
echo "relax 1 calculated with $NN generation" >> log
for i in `seq 2 10`
do
   if [ $NN -gt 3 ]
   then
   mpirun -np ${LSB_DJOB_NUMPROC} vasp_std
   NN=`grep "in kB" OUTCAR  | wc -l`
   cp CONTCAR POSCAR
   cp POSCAR POSCAR$i
   echo "relax $i calculated with $NN generation" >> log
   else
   break
   fi
done
