import subprocess, platform, os

def potcar(pot):
    # Generate POTCAR.
    if pot == "auto":
        if platform.system() == "Linux":
            #get_info.check_vaspkit()
            subprocess.run("vaspkit -task 103 > /dev/null", text=True, shell = True)
            print("<=> Valkyrie: Auto generate POTCAR by vaspkit.")
        else:
            print("<=> Valkyrie: Check under windows, POTCAR is generated autoly")
    else:
        tag = ""
        for i in pot:
            tag = tag + i + "\n"
        if platform.system() == "Linux":
            #get_info.check_vaspkit()
            subprocess.run("vaspkit -task 104", input=tag, text=True, shell=True)
            print("<=> Valkyrie: Generate POTCAR {} by vaspkit.".format(pot))
        else:
            print("<=> Valkyrie: Check under windows, POTCAR is generated by {}".format(pot))
    return 0


if __name__ == "__main__":
    potcar(["Li", "In"])